# Calculating an Option's Expected Value {#ev}

The expected value for each option can be calculated as follows:

\begin{equation} 
E_p(k) = (P_{ae} * C) + (P_{be} * G)
(\#eq:puts)
\end{equation} 

\begin{equation} 
E_c(k) = (P_{be} * C) + (P_{ae} * G)
(\#eq:calls)
\end{equation} 

where  

- $E_p(k)$ is the expected value of a put at strike price $k$
- $E_c(k)$ is the expected value of a call at strike price $k$
- $P_{ae}$ is the probability a security price on the strike date is above the 
_effective price_^[The effective price is the strike price plus the option cost 
(for calls) - you cannot make money on the option until you cross this 
threshold], $k_e$
    - This is calculated with the Monte Carlo simulation
    - $P_{ae} = \frac{r_{ae}}{r_t}$ where $r_{ae}$ is the number of runs above 
    the expected price and $r_t$ are the total runs
- $P_{be}$ = 1 - $P_{ae}$ is the probability a security price on the strike date 
is below the _effective price_, $k_e$
- $C = 100c$ is the cost to buy the option
    - $c$ is the cost of a single option (options are typically bought/sold in 
    lots of 100)
- $G = 100(E_{p_s}(p_s|p_s>k_e) - c)$ is the expected gain if the derivative 
is in the money 
    - $E_{p_s}(p_s|p_s>k_e)$ is the expected value of the of the price of the 
    stock, $p_s$, given that the price of the stock has exceeded the effective 
    price, $k_e$ (for calls).

