--- 
title: "Buying Derivatives - A Monte Carlo Approach"
author: "Jake Rozran"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: RLE-Analytics/iron_financial
description: "This is a strategy for buying puts and calls."
---

# Introduction

Over the course of the last year, I have developed an algorithm that calculates 
the expected outcome for [security derivatives](#link-to-derivatives). To do 
this, I calculate several probabilities and expected values, then combine them to 
understand if it is worthwhile to purchase a security derivative. 

These probabilities are [bootstrapped](#link-to-bootstrap) through the use of a 
[Monte Carlo simulation](#link-to-mc). I am first simulating the price of the 
security on the strike date. I am then able, with this information, to obtain 
the probability the security will be above or below a certain strike and the 
expected value of the security if it does go above (below) the strike for a call 
(put). Combining this with the cost to purchase that derivative, I am able to 
create an expected value for a range of security derivatives. 